// This file is auto-generated by @hey-api/openapi-ts

export { getProducts, getProductsById, type Options } from './sdk.gen';
export type { ClientOptions, GetAllProductsResponse, GetProductsByIdData, GetProductsByIdError, GetProductsByIdErrors, GetProductsByIdResponse, GetProductsByIdResponses, GetProductsData, GetProductsError, GetProductsErrors, GetProductsResponse, GetProductsResponses, ProductParams, ProductResponse, ProductsQuery } from './types.gen';
