// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetProductsByIdData, GetProductsByIdErrors, GetProductsByIdResponses, GetProductsData, GetProductsErrors, GetProductsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Get product by id
 */
export const getProductsById = <ThrowOnError extends boolean = false>(options?: Options<GetProductsByIdData, ThrowOnError>): RequestResult<GetProductsByIdResponses, GetProductsByIdErrors, ThrowOnError> => (options?.client ?? client).get<GetProductsByIdResponses, GetProductsByIdErrors, ThrowOnError>({ url: '/products/{id}', ...options });

/**
 * Get products
 */
export const getProducts = <ThrowOnError extends boolean = false>(options?: Options<GetProductsData, ThrowOnError>): RequestResult<GetProductsResponses, GetProductsErrors, ThrowOnError> => (options?.client ?? client).get<GetProductsResponses, GetProductsErrors, ThrowOnError>({ url: '/products', ...options });
