// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

export type ProductParams = {
    id: number | null;
};

export type ProductsQuery = {
    search?: string;
    sort?: string;
    limit?: number;
    offset?: number | null;
    name?: string;
    price_min?: number | null;
    price_max?: number | null;
};

export type GetAllProductsResponse = {
    status: 'success';
    data: {
        products: Array<{
            id: number;
            name: string;
            price: string;
            isActive: boolean;
        }>;
        hasNext: boolean;
        totalCount: number;
    };
};

export type ProductResponse = {
    status: 'success';
    data: {
        id: number;
        name: string;
        price: string;
        isActive: boolean;
    };
};

export type GetProductsByIdData = {
    body?: never;
    path?: {
        id?: number | null;
    };
    query?: never;
    url: '/products/{id}';
};

export type GetProductsByIdErrors = {
    /**
     * Internal Server Error
     */
    500: {
        status: 'failure';
        message: string;
    };
};

export type GetProductsByIdError = GetProductsByIdErrors[keyof GetProductsByIdErrors];

export type GetProductsByIdResponses = {
    /**
     * Product
     */
    200: {
        status: 'success';
        data: {
            id: number;
            name: string;
            price: string;
            isActive: boolean;
        };
    };
};

export type GetProductsByIdResponse = GetProductsByIdResponses[keyof GetProductsByIdResponses];

export type GetProductsData = {
    body?: never;
    path?: never;
    query?: {
        search?: string;
        sort?: string;
        limit?: number;
        offset?: number | null;
        name?: string;
        price_min?: number | null;
        price_max?: number | null;
    };
    url: '/products';
};

export type GetProductsErrors = {
    /**
     * Internal Server Error
     */
    500: {
        status: 'failure';
        message: string;
    };
};

export type GetProductsError = GetProductsErrors[keyof GetProductsErrors];

export type GetProductsResponses = {
    /**
     * Product
     */
    200: {
        status: 'success';
        data: {
            products: Array<{
                id: number;
                name: string;
                price: string;
                isActive: boolean;
            }>;
            hasNext: boolean;
            totalCount: number;
        };
    };
};

export type GetProductsResponse = GetProductsResponses[keyof GetProductsResponses];
